# Generated by Django 4.1.1 on 2022-09-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_purchase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
